name: CU Cyber
url: https://cucyber.net
twitter: '@CU_Cyber'
description: |
  CU Cyber is a student led organization at Clemson University that focuses on the technical and social aspects of cyber security

timezone: America/New_York

exclude: ['CNAME']

host: localhost
port: 8080
